In [2]:
!pip install pandas

Requirement already satisfied: pandas in d:\downloads\social-listening-platform\social-listening-platform\.venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in d:\downloads\social-listening-platform\social-listening-platform\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\downloads\social-listening-platform\social-listening-platform\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\downloads\social-listening-platform\social-listening-platform\.venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in d:\downloads\social-listening-platform\social-listening-platform\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: There was an error checking the latest version of pip.

In [3]:
# read_social_listening_db.py
import os
import sqlite3
import pandas as pd

DB_PATH = "social_listening.db"

if not os.path.exists(DB_PATH):
    raise FileNotFoundError(f"{DB_PATH} not found in current directory")

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';")
tables = [r[0] for r in cur.fetchall()]
print("Tables:", tables)

for table in tables:
    print(f"\n--- Table: {table} ---")
    cur.execute(f"PRAGMA table_info({table})")
    schema = [(c[1], c[2]) for c in cur.fetchall()]
    print("Schema:", schema)
    df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 100", conn)
    print(df.head())

cur.close()
conn.close()

Tables: ['topics', 'posts', 'pain_points', 'notifications']

--- Table: topics ---
Schema: [('id', 'VARCHAR(36)'), ('owner_id', 'VARCHAR(36)'), ('name', 'VARCHAR(255)'), ('keywords', 'JSON'), ('sources', 'JSON'), ('source_configs', 'JSON'), ('alert_threshold', 'INTEGER'), ('notifications_enabled', 'BOOLEAN'), ('created_at', 'DATETIME')]
                                     id                              owner_id  \
0  cdca391f-4bcc-44a6-88b8-0b26541a8af2  00000000-0000-0000-0000-000000000001
1  ef9fca45-9e13-4c08-b48a-537e337f6e94  00000000-0000-0000-0000-000000000001
2  f8b8a06a-fe69-49d4-bf36-0d44a3578a77  00000000-0000-0000-0000-000000000001
3  2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa  00000000-0000-0000-0000-000000000001
4  0787eded-c5f9-4d91-8987-54f88da239b7  00000000-0000-0000-0000-000000000001

          name                           keywords  \
0  Techcombank             ["techcombank", "tcb"]
1  Vietcombank             ["vietcombank", "vcb"]
2      MB Bank              ["mb bank", "mbbank"]
3          SHB  ["shb", "saha", "sai gon ha noi"]
4       TPBank              ["tpbank", "tp bank"]

                        sources  \
0  ["google_play", "app_store"]
1  ["google_play", "app_store"]
2  ["google_play", "app_store"]
3  ["google_play", "app_store"]
4  ["google_play", "app_store"]

                                      source_configs  alert_threshold  \
0  {"google_play": {"app_id": "vn.com.techcombank...               10
1  {"google_play": {"app_id": "com.VCB"}, "app_st...               15
2  {"google_play": {"app_id": "com.mbmobile"}, "a...                8
3  {"google_play": {"app_id": "vn.shb.saha.mbanki...               10
4  {"google_play": {"app_id": "com.tpb.mb.gprsand...               10

   notifications_enabled                  created_at
0                      1  2026-08-03 15:23:23.295916
1                      1  2026-08-03 15:23:23.295916
2                      0  2026-08-03 15:23:23.295916
3                      1  2026-08-04 08:55:15.100405
4                      1  2026-08-04 08:55:15.100405

--- Table: posts ---
Schema: [('id', 'VARCHAR(36)'), ('topic_id', 'VARCHAR(36)'), ('source', 'VARCHAR(50)'), ('author', 'VARCHAR(255)'), ('content', 'TEXT'), ('content_hash', 'VARCHAR(64)'), ('published_at', 'DATETIME'), ('collected_at', 'DATETIME'), ('is_duplicate', 'BOOLEAN'), ('is_spam', 'BOOLEAN'), ('sentiment', 'VARCHAR(20)'), ('topic_label', 'VARCHAR(50)'), ('severity_score', 'FLOAT')]
                                     id                              topic_id  \
0  8f74460c-df1f-4cb7-9e6b-a11fbda629c7  cdca391f-4bcc-44a6-88b8-0b26541a8af2
1  d08a4c1f-cd13-4d6b-a7a7-a6321e10e82a  cdca391f-4bcc-44a6-88b8-0b26541a8af2
2  21f65f4a-dd69-4b0e-adc0-cb0f1f2c2664  cdca391f-4bcc-44a6-88b8-0b26541a8af2
3  6d27e4f7-cda8-4d6d-b3b6-f4ba5217b0fc  cdca391f-4bcc-44a6-88b8-0b26541a8af2
4  f60005c4-6be7-4c03-bda5-06435f3e756b  cdca391f-4bcc-44a6-88b8-0b26541a8af2

        source             author  \
0  google_play         Duyvu Pham
1  google_play             Vu Kin
2  google_play          Truyền Lý
3  google_play  Nguyễn Toàn Trung
4  google_play        viet habinh

                                             content  \
0                                                 ok
1                                             rất OK
2                                ok nha mn, nên dùng
3  app thường xuyên bị lỗi. k đăng nhập đc. trải ...
4                                               4sao

                                        content_hash  \
0  8c609c828bf91527321bc0cda8c703de8eada7ab0d44f3...
1  dd052a8308330533f6547631c418e903032d2b37b00cc2...
2  dde1a5478212468d9b17ee29703abd9764e248320fbcfa...
3  613d5674136543d559c1f3f087571dc6481d35d414bdad...
4  4465b812b8a2a730fd2a79d3de0979da4a8500e1292ecf...

                 published_at                collected_at  is_duplicate  \
0  2026-08-02 21:43:51.000000  2026-08-03 15:23:23.722654             0
1  2026-08-02 20:47:39.000000  2026-08-03 15:23:23.722654             0
2  2026-08-02 20:27:11.000000  2026-08-03 15:23:23.722654             0
3  2026-08-02 19:35:55.000000  2026-08-03 15:23:23.722654             0
4  2026-08-02 19:10:12.000000  2026-08-03 15:23:23.722654             0

   is_spam sentiment topic_label  severity_score
0        0   neutral     dich_vu            0.04
1        0   neutral     dich_vu            0.26
2        0   neutral     dich_vu            0.30
3        0  negative   dang_nhap            0.80
4        0   neutral     dich_vu            0.24

--- Table: pain_points ---
Schema: [('id', 'VARCHAR(36)'), ('topic_id', 'VARCHAR(36)'), ('title', 'VARCHAR(500)'), ('description', 'TEXT'), ('post_count', 'INTEGER'), ('trend', 'VARCHAR(10)'), ('severity', 'VARCHAR(20)'), ('verification_status', 'VARCHAR(20)'), ('confidence_score', 'FLOAT'), ('sources', 'JSON'), ('sample_posts', 'JSON'), ('created_at', 'DATETIME'), ('status', 'VARCHAR(20)'), ('assignee', 'VARCHAR(255)'), ('resolution_notes', 'TEXT'), ('resolved_at', 'DATETIME'), ('topic_label', 'VARCHAR(50)')]
                                     id                              topic_id  \
0  0c3debdb-794e-4798-a2a0-2042fc6d2265  cdca391f-4bcc-44a6-88b8-0b26541a8af2
1  9156b649-8497-4f98-b983-eb4c2d8b5d3b  cdca391f-4bcc-44a6-88b8-0b26541a8af2
2  32aab6ba-5085-4f94-bd51-147426da9272  cdca391f-4bcc-44a6-88b8-0b26541a8af2
3  0ae192bb-9e54-4382-857e-746f30dc7025  cdca391f-4bcc-44a6-88b8-0b26541a8af2
4  bab37a5a-e443-489b-9e6b-e5c7ae7c4bd9  cdca391f-4bcc-44a6-88b8-0b26541a8af2

                                        title  \
0                    Lỗi đăng nhập / xác thực
1                    Lỗi ứng dụng / hiệu năng
2                 Lỗi giao dịch / chuyển tiền
3                Chất lượng dịch vụ nói chung
4  Thái độ / chất lượng phục vụ của nhân viên

                                         description  post_count trend  \
0  34 phản hồi tiêu cực liên quan đến "lỗi đăng n...          46    up
1  100 phản hồi tiêu cực liên quan đến "lỗi ứng d...         113    up
2  67 phản hồi tiêu cực liên quan đến "lỗi giao d...          82    up
3  78 phản hồi tiêu cực liên quan đến "chất lượng...          95    up
4  15 phản hồi tiêu cực liên quan đến "thái độ / ...          17    up

  severity verification_status  confidence_score sources  \
0     high        needs_review              0.78      []
1   medium        needs_review              0.77      []
2   medium        needs_review              0.78      []
3   medium        needs_review              0.78      []
4   medium        needs_review              0.78      []

                                        sample_posts  \
0  ["kh\u00f4ng c\u00e0i l\u1ea1i m\u1eadt kh\u1e...
1  ["b\u1ecb l\u1ed7i kh\u00f4ng v\u00e0o app \u0...
2  ["t\u00e0i kho\u1ea3n tr\u1eeb ti\u1ec1n r nh\...
3  ["li\u00ean t\u1ee5c b\u00e1o l\u1ed7i 9999 gi...
4  ["\u1ee9ng d\u1ee5ng r\u1ea5t t\u1ec7 , ch\u01...

                   created_at status assignee resolution_notes resolved_at  \
0  2026-08-04 15:39:57.355249   open     None             None        None
1  2026-08-04 15:39:57.355249   open     None             None        None
2  2026-08-04 15:39:57.355249   open     None             None        None
3  2026-08-04 15:39:57.355249   open     None             None        None
4  2026-08-04 15:39:57.355249   open     None             None        None

  topic_label
0   dang_nhap
1    ung_dung
2   giao_dich
3     dich_vu
4   nhan_vien

--- Table: notifications ---
Schema: [('id', 'VARCHAR(36)'), ('topic_id', 'VARCHAR(36)'), ('pain_point_id', 'VARCHAR(36)'), ('channel', 'VARCHAR(20)'), ('title', 'VARCHAR(500)'), ('message', 'TEXT'), ('sent_at', 'DATETIME'), ('read', 'BOOLEAN')]
                                     id                              topic_id  \
0  04399cd9-c5ad-4d92-9853-00f3c141584c  cdca391f-4bcc-44a6-88b8-0b26541a8af2
1  932de989-6cc5-4439-b46a-32180c969344  cdca391f-4bcc-44a6-88b8-0b26541a8af2
2  ecc99a2f-efd6-4298-8ead-bd2e555ab508  cdca391f-4bcc-44a6-88b8-0b26541a8af2
3  1506612d-5d82-4508-b653-c1ff5f0c23d0  cdca391f-4bcc-44a6-88b8-0b26541a8af2
4  628bf9b1-b066-476f-848f-ea8ba20d0a3f  ef9fca45-9e13-4c08-b48a-537e337f6e94

                          pain_point_id channel                         title  \
0  0c3debdb-794e-4798-a2a0-2042fc6d2265    both      Lỗi đăng nhập / xác thực
1  9156b649-8497-4f98-b983-eb4c2d8b5d3b    both      Lỗi ứng dụng / hiệu năng
2  32aab6ba-5085-4f94-bd51-147426da9272    both   Lỗi giao dịch / chuyển tiền
3  0ae192bb-9e54-4382-857e-746f30dc7025    both  Chất lượng dịch vụ nói chung
4  0d72313a-a220-4390-9f59-259b5cfe3e4d    both      Lỗi ứng dụng / hiệu năng

                                             message  \
0  12 phản hồi tiêu cực liên quan đến "lỗi đăng n...
1  13 phản hồi tiêu cực liên quan đến "lỗi ứng dụ...
2  15 phản hồi tiêu cực liên quan đến "lỗi giao d...
3  17 phản hồi tiêu cực liên quan đến "chất lượng...
4  26 phản hồi tiêu cực liên quan đến "lỗi ứng dụ...

                      sent_at  read
0  2026-08-04 15:39:57.380005     0
1  2026-08-04 15:39:57.380005     0
2  2026-08-04 15:39:57.380005     0
3  2026-08-04 15:39:57.380005     0
4  2026-08-04 15:39:57.408864     0

In [4]:
from IPython.display import display

pd.set_option("display.max_colwidth", 120)
pd.set_option("display.max_rows", 40)
pd.set_option("display.width", 150)
pd.set_option("display.colheader_justify", "left")

readable_table = df.copy()
readable_table["sent_at"] = pd.to_datetime(readable_table["sent_at"])

display(readable_table)

,id,topic_id,pain_point_id,channel,title,message,sent_at,read
0,04399cd9-c5ad-4d92-9853-00f3c141584c,cdca391f-4bcc-44a6-88b8-0b26541a8af2,0c3debdb-794e-4798-a2a0-2042fc6d2265,both,Lỗi đăng nhập / xác thực,"12 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",2026-08-04 15:39:57.380005,0
1,932de989-6cc5-4439-b46a-32180c969344,cdca391f-4bcc-44a6-88b8-0b26541a8af2,9156b649-8497-4f98-b983-eb4c2d8b5d3b,both,Lỗi ứng dụng / hiệu năng,"13 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",2026-08-04 15:39:57.380005,0
2,ecc99a2f-efd6-4298-8ead-bd2e555ab508,cdca391f-4bcc-44a6-88b8-0b26541a8af2,32aab6ba-5085-4f94-bd51-147426da9272,both,Lỗi giao dịch / chuyển tiền,"15 phản hồi tiêu cực liên quan đến ""lỗi giao dịch / chuyển tiền"".",2026-08-04 15:39:57.380005,0
3,1506612d-5d82-4508-b653-c1ff5f0c23d0,cdca391f-4bcc-44a6-88b8-0b26541a8af2,0ae192bb-9e54-4382-857e-746f30dc7025,both,Chất lượng dịch vụ nói chung,"17 phản hồi tiêu cực liên quan đến ""chất lượng dịch vụ nói chung"".",2026-08-04 15:39:57.380005,0
4,628bf9b1-b066-476f-848f-ea8ba20d0a3f,ef9fca45-9e13-4c08-b48a-537e337f6e94,0d72313a-a220-4390-9f59-259b5cfe3e4d,both,Lỗi ứng dụng / hiệu năng,"26 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",2026-08-04 15:39:57.408864,0
...,...,...,...,...,...,...,...,...
37,9ee29e10-fecb-40be-a700-f4e1d430d49f,0787eded-c5f9-4d91-8987-54f88da239b7,ad3b1cc8-9fd1-41e6-a3d9-40e35f7185cd,both,Lỗi đăng nhập / xác thực,"46 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",2026-08-04 17:19:29.535660,0
38,8eec7509-b12c-43c0-b25b-6b3e998cb566,0787eded-c5f9-4d91-8987-54f88da239b7,0e4e38c1-b0b0-4cde-aa00-6f7c37cf4752,both,Bảo mật / khoá tài khoản,"17 phản hồi tiêu cực liên quan đến ""bảo mật / khoá tài khoản"".",2026-08-04 17:19:29.535660,0
39,8a8d9cfe-4a97-46d2-b087-27244e80331b,0787eded-c5f9-4d91-8987-54f88da239b7,69293a43-73e7-4873-8374-350d417f66fe,both,Lỗi ứng dụng / hiệu năng,"98 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",2026-08-04 17:19:29.535660,0
40,8ccd6547-5176-419c-ac81-7118d6aeb4d5,0787eded-c5f9-4d91-8987-54f88da239b7,e29414ca-506c-4197-b4e0-e786306195a2,both,Thái độ / chất lượng phục vụ của nhân viên,"59 phản hồi tiêu cực liên quan đến ""thái độ / chất lượng phục vụ của nhân viên"".",2026-08-04 17:19:29.535660,0
41,7f6824d5-ebf3-4081-a1df-8787eeab3d53,0787eded-c5f9-4d91-8987-54f88da239b7,b4011456-ff4c-4220-a202-d34935b77861,both,Chính sách / biểu phí,"17 phản hồi tiêu cực liên quan đến ""chính sách / biểu phí"".",2026-08-04 17:19:29.535660,0

In [5]:
# Đọc tất cả các bảng trong DB_PATH vào dict các DataFrame và hiển thị
conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';")
tables = [r[0] for r in cur.fetchall()]

tables_dfs = {}
for table in tables:
    tables_dfs[table] = pd.read_sql_query(f'SELECT * FROM "{table}"', conn)
    print(f"\n--- Table: {table} ({len(tables_dfs[table])} rows, {len(tables_dfs[table].columns)} cols) ---")
    display(tables_dfs[table].head(100))

cur.close()
conn.close()

--- Table: topics (5 rows, 9 cols) ---

,id,owner_id,name,keywords,sources,source_configs,alert_threshold,notifications_enabled,created_at
0,cdca391f-4bcc-44a6-88b8-0b26541a8af2,00000000-0000-0000-0000-000000000001,Techcombank,"[""techcombank"", ""tcb""]","[""google_play"", ""app_store""]","{""google_play"": {""app_id"": ""vn.com.techcombank.bb.app""}, ""app_store"": {""app_id"": ""1548623362"", ""country"": ""vn""}}",10,1,2026-08-03 15:23:23.295916
1,ef9fca45-9e13-4c08-b48a-537e337f6e94,00000000-0000-0000-0000-000000000001,Vietcombank,"[""vietcombank"", ""vcb""]","[""google_play"", ""app_store""]","{""google_play"": {""app_id"": ""com.VCB""}, ""app_store"": {""app_id"": ""561433133"", ""country"": ""vn""}}",15,1,2026-08-03 15:23:23.295916
2,f8b8a06a-fe69-49d4-bf36-0d44a3578a77,00000000-0000-0000-0000-000000000001,MB Bank,"[""mb bank"", ""mbbank""]","[""google_play"", ""app_store""]","{""google_play"": {""app_id"": ""com.mbmobile""}, ""app_store"": {""app_id"": ""1205807363"", ""country"": ""vn""}}",8,0,2026-08-03 15:23:23.295916
3,2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa,00000000-0000-0000-0000-000000000001,SHB,"[""shb"", ""saha"", ""sai gon ha noi""]","[""google_play"", ""app_store""]","{""google_play"": {""app_id"": ""vn.shb.saha.mbanking""}, ""app_store"": {""app_id"": ""1661457183"", ""country"": ""vn""}}",10,1,2026-08-04 08:55:15.100405
4,0787eded-c5f9-4d91-8987-54f88da239b7,00000000-0000-0000-0000-000000000001,TPBank,"[""tpbank"", ""tp bank""]","[""google_play"", ""app_store""]","{""google_play"": {""app_id"": ""com.tpb.mb.gprsandroid""}, ""app_store"": {""app_id"": ""450464147"", ""country"": ""vn""}}",10,1,2026-08-04 08:55:15.100405

--- Table: posts (3552 rows, 13 cols) ---

,id,topic_id,source,author,content,content_hash,published_at,collected_at,is_duplicate,is_spam,sentiment,topic_label,severity_score
0,8f74460c-df1f-4cb7-9e6b-a11fbda629c7,cdca391f-4bcc-44a6-88b8-0b26541a8af2,google_play,Duyvu Pham,ok,8c609c828bf91527321bc0cda8c703de8eada7ab0d44f33cff4498904e606bf6,2026-08-02 21:43:51.000000,2026-08-03 15:23:23.722654,0,0,neutral,dich_vu,0.04
1,d08a4c1f-cd13-4d6b-a7a7-a6321e10e82a,cdca391f-4bcc-44a6-88b8-0b26541a8af2,google_play,Vu Kin,rất OK,dd052a8308330533f6547631c418e903032d2b37b00cc27ef9f961e54b805b48,2026-08-02 20:47:39.000000,2026-08-03 15:23:23.722654,0,0,neutral,dich_vu,0.26
2,21f65f4a-dd69-4b0e-adc0-cb0f1f2c2664,cdca391f-4bcc-44a6-88b8-0b26541a8af2,google_play,Truyền Lý,"ok nha mn, nên dùng",dde1a5478212468d9b17ee29703abd9764e248320fbcfa212f2d61e36e599be8,2026-08-02 20:27:11.000000,2026-08-03 15:23:23.722654,0,0,neutral,dich_vu,0.30
3,6d27e4f7-cda8-4d6d-b3b6-f4ba5217b0fc,cdca391f-4bcc-44a6-88b8-0b26541a8af2,google_play,Nguyễn Toàn Trung,app thường xuyên bị lỗi. k đăng nhập đc. trải nghiệm tệ so với các ngân hàng khác. nếu k vì tài khoản có nhiều người...,613d5674136543d559c1f3f087571dc6481d35d414bdad4dbcd88e664f65c51d,2026-08-02 19:35:55.000000,2026-08-03 15:23:23.722654,0,0,negative,dang_nhap,0.80
4,f60005c4-6be7-4c03-bda5-06435f3e756b,cdca391f-4bcc-44a6-88b8-0b26541a8af2,google_play,viet habinh,4sao,4465b812b8a2a730fd2a79d3de0979da4a8500e1292ecff6f78b8409b50b81d2,2026-08-02 19:10:12.000000,2026-08-03 15:23:23.722654,0,0,neutral,dich_vu,0.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0e29c884-ae27-4833-a693-b127e748fb12,ef9fca45-9e13-4c08-b48a-537e337f6e94,google_play,Nguyễn Hồng Yên,"Ứng dụng đang bị lỗi ở mục thẻ, không cho mở tác vụ này",cffc635c421112002934433b14d32afd3570936a2b3c5107bda45b8a6ed8d023,2026-08-02 17:02:25.000000,2026-08-03 15:23:52.923859,0,0,negative,ung_dung,0.70
96,1c6f6797-82cd-4cf0-a26c-37feacda0ae7,ef9fca45-9e13-4c08-b48a-537e337f6e94,google_play,Viet Thanh Dau,không gửi VCB Smart OTP về,226178974f53507152e1c6d706cfce558ab09895476248d8ee0b488996d15aa9,2026-08-02 16:32:09.000000,2026-08-03 15:23:52.923859,0,0,negative,dang_nhap,0.60
97,6675e0d8-f590-4f4b-b205-5dff6bde0584,ef9fca45-9e13-4c08-b48a-537e337f6e94,google_play,Đăk chong A kem,vào bị treo lỗi quá lỗi,7d46222c6040f8a2d1612a379123cb2428b3f5b0ca44e15179604256082a9adc,2026-08-02 15:24:27.000000,2026-08-03 15:23:52.923859,0,0,negative,ung_dung,0.60
98,6726fafd-3447-4891-afa2-b011f633435b,ef9fca45-9e13-4c08-b48a-537e337f6e94,google_play,Thiên Ân Nguyễn,"chuyển thiết bị phải đặt lại smart otp mà không được đổi trùng, phiền thật, nên giảm thời gian dùng lại mã cũ khoảng...",2c729395926268ccf23b0e0e7b3b0ce9594b80369c5743cb94ce84c143dc9fb7,2026-08-02 14:58:31.000000,2026-08-03 15:23:52.923859,0,0,negative,dang_nhap,0.70
99,82fce607-a970-4fc3-833a-ebad6b5df603,ef9fca45-9e13-4c08-b48a-537e337f6e94,google_play,Phương Dạ Ly Cửu,cứ bắt tạo mã xác thực trong khi đã tạo r là saooo,b7a9d73a1eb17b08ba598cf975ebff6107069cd77ce69c42afb934f032b87f9c,2026-08-02 13:35:01.000000,2026-08-03 15:23:52.923859,0,0,neutral,dang_nhap,0.11

--- Table: pain_points (35 rows, 17 cols) ---

,id,topic_id,title,description,post_count,trend,severity,verification_status,confidence_score,sources,sample_posts,created_at,status,assignee,resolution_notes,resolved_at,topic_label
0,0c3debdb-794e-4798-a2a0-2042fc6d2265,cdca391f-4bcc-44a6-88b8-0b26541a8af2,Lỗi đăng nhập / xác thực,"34 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",46,up,high,needs_review,0.78,[],"[""kh\u00f4ng c\u00e0i l\u1ea1i m\u1eadt kh\u1ea9u \u0111\u01b0\u1ee3c, to\u00e0n b\u1ecb b\u00e1o l\u1ed7i gi\u00e1n...",2026-08-04 15:39:57.355249,open,None,None,None,dang_nhap
1,9156b649-8497-4f98-b983-eb4c2d8b5d3b,cdca391f-4bcc-44a6-88b8-0b26541a8af2,Lỗi ứng dụng / hiệu năng,"100 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",113,up,medium,needs_review,0.77,[],"[""b\u1ecb l\u1ed7i kh\u00f4ng v\u00e0o app \u0111\u01b0\u1ee3c mong nh\u00e0 ph\u00e1t h\u00e0nh kh\u1eafc ph\u1ee5c...",2026-08-04 15:39:57.355249,open,None,None,None,ung_dung
2,32aab6ba-5085-4f94-bd51-147426da9272,cdca391f-4bcc-44a6-88b8-0b26541a8af2,Lỗi giao dịch / chuyển tiền,"67 phản hồi tiêu cực liên quan đến ""lỗi giao dịch / chuyển tiền"".",82,up,medium,needs_review,0.78,[],"[""t\u00e0i kho\u1ea3n tr\u1eeb ti\u1ec1n r nh\u01b0ng b\u00ean kia m\u00e3i ko nh\u1eadn \u0111c li\u00ean h\u1ec7 g...",2026-08-04 15:39:57.355249,open,None,None,None,giao_dich
3,0ae192bb-9e54-4382-857e-746f30dc7025,cdca391f-4bcc-44a6-88b8-0b26541a8af2,Chất lượng dịch vụ nói chung,"78 phản hồi tiêu cực liên quan đến ""chất lượng dịch vụ nói chung"".",95,up,medium,needs_review,0.78,[],"[""li\u00ean t\u1ee5c b\u00e1o l\u1ed7i 9999 gi\u00e1n \u0111o\u1ea1n, ko v\u00e0o \u0111c app"", ""Chuy\u1ec3n c\u00f3...",2026-08-04 15:39:57.355249,open,None,None,None,dich_vu
4,bab37a5a-e443-489b-9e6b-e5c7ae7c4bd9,cdca391f-4bcc-44a6-88b8-0b26541a8af2,Thái độ / chất lượng phục vụ của nhân viên,"15 phản hồi tiêu cực liên quan đến ""thái độ / chất lượng phục vụ của nhân viên"".",17,up,medium,needs_review,0.78,[],"[""\u1ee9ng d\u1ee5ng r\u1ea5t t\u1ec7 , ch\u0103m s\u00f3c kh\u00e1ch h\u00e0ng t\u1ec7 , app b\u1ecb l\u1ed7i 9999 ...",2026-08-04 15:39:57.355249,open,None,None,None,nhan_vien
5,0d72313a-a220-4390-9f59-259b5cfe3e4d,ef9fca45-9e13-4c08-b48a-537e337f6e94,Lỗi ứng dụng / hiệu năng,"131 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",158,up,medium,needs_review,0.78,[],"[""v\u00e0o app. v\u00e0o th\u1ebb \u0111\u1ec3 thanh go\u00e1n th\u00ec v\u0103ng ra. m\u1ea5y ngay k \u0111\u01b0\u...",2026-08-04 15:39:57.394307,open,None,None,None,ung_dung
6,4ec26078-4590-4e96-a2c3-2722bf20349b,ef9fca45-9e13-4c08-b48a-537e337f6e94,Lỗi giao dịch / chuyển tiền,"68 phản hồi tiêu cực liên quan đến ""lỗi giao dịch / chuyển tiền"".",86,up,medium,needs_review,0.80,[],"[""Ck \u0111\u00e3 tr\u1eeb ti\u1ec1n nh\u01b0ng b\u00ean kia ch\u01b0a nh\u1eadn \u0111\u01b0\u1ee3c, g\u1ecdi l\u1e...",2026-08-04 15:39:57.394307,open,None,None,None,giao_dich
7,d52c7b54-c6eb-40cf-9fb8-7d146f7b063f,ef9fca45-9e13-4c08-b48a-537e337f6e94,Chất lượng dịch vụ nói chung,"99 phản hồi tiêu cực liên quan đến ""chất lượng dịch vụ nói chung"".",123,up,medium,needs_review,0.78,[],"[""T\u1ea1o tk m\u1edbi n\u00f3 b\u1eaft ch\u1ee5p h\u00ecnh ho\u00e0i ch\u1ee5p ho\u00e0i m\u00e0 n\u00f3 n\u00f3i k...",2026-08-04 15:39:57.394307,open,None,None,None,dich_vu
8,8e31d580-80ee-4d8d-86f7-dbe618619fcb,ef9fca45-9e13-4c08-b48a-537e337f6e94,Lỗi đăng nhập / xác thực,"90 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",110,up,medium,needs_review,0.79,[],"[""kh\u00f4ng bi\u1ebft do \u00e1p hay do \u0111t m\u00e0 \u0111\u0103ng nh\u1eadp v\u00e0o c\u1ee9 vcb digibank bu\u...",2026-08-04 15:39:57.394307,open,None,None,None,dang_nhap
9,155f09ff-4b4b-4508-8c64-06be90a19638,ef9fca45-9e13-4c08-b48a-537e337f6e94,Bảo mật / khoá tài khoản,"2 phản hồi tiêu cực liên quan đến ""bảo mật / khoá tài khoản"".",3,up,high,needs_review,0.86,[],"[""\u0110i\u00ean thoai s\u00e0i c\u1ea3 ch\u1ee5c n\u0103m sai app nao cug dk..Gio t\u01b0 nhi\u00ean chi co mo khoa...",2026-08-04 15:39:57.394307,open,None,None,None,bao_mat
10,a4dcc075-e82c-4b1c-a3d4-e8553796c26c,ef9fca45-9e13-4c08-b48a-537e337f6e94,Thái độ / chất lượng phục vụ của nhân viên,"23 phản hồi tiêu cực liên quan đến ""thái độ / chất lượng phục vụ của nhân viên"".",25,up,medium,needs_review,0.75,[],"[""Ng\u01b0\u1eddi nh\u00e0 kh\u00f4ng bi\u1ebft l\u00e0m g\u1ecdi t\u1ed5ng \u0111\u00e0i h\u1ed7 tr\u1ee3 b\u1eaft ...",2026-08-04 15:39:57.394307,open,None,None,None,nhan_vien
11,bbe8fbfe-0f5b-4285-8d25-dbd6946547f2,f8b8a06a-fe69-49d4-bf36-0d44a3578a77,Lỗi ứng dụng / hiệu năng,"48 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",55,up,medium,needs_review,0.78,[],"[""App MB b\u1eaft update nhi\u1ec1u qu\u00e1 , m\u1ea5y ng\u00e0y l\u1ea1i update, nhi\u1ec1u khi to\u00e0n treo h\u...",2026-08-04 15:39:57.416876,open,None,None,None,ung_dung
12,2f19d9c8-6bad-4629-99b3-8225d2a0e12a,f8b8a06a-fe69-49d4-bf36-0d44a3578a77,Chất lượng dịch vụ nói chung,"69 phản hồi tiêu cực liên quan đến ""chất lượng dịch vụ nói chung"".",85,up,medium,needs_review,0.79,[],"[""\u0110\u0103ng k\u00fd tk c\u1ee9 b\u00e1o l\u1ed7i ,ch\u1ee5p cccd c\u1ee9 b\u1ea3o m\u1edd nh\u01b0ng m\u00e0 n\...",2026-08-04 15:39:57.416876,open,None,None,None,dich_vu
13,876a17d0-485e-4cca-90a5-c887d04c5eb5,f8b8a06a-fe69-49d4-bf36-0d44a3578a77,Lỗi giao dịch / chuyển tiền,"67 phản hồi tiêu cực liên quan đến ""lỗi giao dịch / chuyển tiền"".",88,up,medium,needs_review,0.78,[],"[""app g\u00ec m\u00e0 m\u1edf ch\u1ea1y r\u1ea5t l\u00e0 ch\u1eadm th\u1ea5y m\u00e0 ph\u00e1t ch\u00e1n ! m\u1ea5t ...",2026-08-04 15:39:57.416876,open,None,None,None,giao_dich
14,812659c5-7bd2-4548-b94f-434780017e0d,f8b8a06a-fe69-49d4-bf36-0d44a3578a77,Thái độ / chất lượng phục vụ của nhân viên,"12 phản hồi tiêu cực liên quan đến ""thái độ / chất lượng phục vụ của nhân viên"".",14,up,high,needs_review,0.78,[],"[""m\u1ea5t ti\u1ec1n,l\u1ed7i kh\u00f4ng \u0111\u01b0\u1ee3c h\u1ed7 tr\u1ee3"", ""app kh\u00f4ng r\u00f5 r\u00e0ng v\...",2026-08-04 15:39:57.416876,open,None,None,None,nhan_vien
15,e2882c3e-5832-42ff-ae8b-357ba81b8ab5,f8b8a06a-fe69-49d4-bf36-0d44a3578a77,Lỗi đăng nhập / xác thực,"15 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",17,up,high,needs_review,0.76,[],"[""b\u1ecb kh\u00f3a D-OTP m\u00e0 thi\u1ebft b\u1ecb c\u0169 kh\u00f4ng \u0111\u0103ng nh\u1eadp v\u00e0o \u0111\u01...",2026-08-04 15:39:57.416876,open,None,None,None,dang_nhap
16,10184703-7cb9-4757-9d00-cccbb31e5a0b,f8b8a06a-fe69-49d4-bf36-0d44a3578a77,Chính sách / biểu phí,"8 phản hồi tiêu cực liên quan đến ""chính sách / biểu phí"".",9,up,medium,needs_review,0.80,[],"[""R\u00fat kh\u00f4ng th\u00e0nh c\u00f4ng c\u0169ng tr\u1eeb ph\u00ed app. Tho\u00e1t ra ngo\u00e0i m\u00e0n h\u00e...",2026-08-04 15:39:57.416876,open,None,None,None,chinh_sach
17,b875681d-9f98-48e6-87d0-81687f3ef7df,2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa,Chất lượng dịch vụ nói chung,"150 phản hồi tiêu cực liên quan đến ""chất lượng dịch vụ nói chung"".",166,up,medium,needs_review,0.77,[],"[""ap wa t\u1ec7 b\u1ecb l\u1ed7i li\u00ean t\u1ee5c kh\u00f4ng v\u00e0o \u0111\u01b0\u1ee3c"", ""M\u1edf tk kh\u00f4ng...",2026-08-04 15:39:57.436653,open,None,None,None,dich_vu
18,ba30632f-438b-4f5d-90a7-2e0ef7c40846,2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa,Lỗi ứng dụng / hiệu năng,"132 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",153,up,medium,needs_review,0.75,[],"[""app l\u1ed7i, m\u1edf m\u00e0n h\u00ecnh ch\u1edd m\u00e3i kh\u00f4ng \u0111\u01b0\u1ee3c, t\u1ea3i l\u1ea1i c\u01...",2026-08-04 15:39:57.436653,open,None,None,None,ung_dung
19,28cbd133-8939-448c-b87c-2edb546a8a00,2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa,Lỗi đăng nhập / xác thực,"99 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",112,up,medium,needs_review,0.78,[],"[""C\u00f3 m\u1ed7i vi\u1ec7c ch\u1ee5p \u1ea3nh c\u0103n c\u01b0\u1edbc \u0111\u1ec3 x\u00e1c th\u1ef1c m\u00e0 n\u1...",2026-08-04 15:39:57.436653,open,None,None,None,dang_nhap
20,06aa50eb-961d-4c8b-8b68-9e2c38b28c7e,2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa,Lỗi giao dịch / chuyển tiền,"67 phản hồi tiêu cực liên quan đến ""lỗi giao dịch / chuyển tiền"".",80,up,high,needs_review,0.77,[],"[""App t\u1ec7 vch , r\u00f5 tr\u1eeb ti\u1ec1n r m\u00e0 b\u00ean kia kjoong nh\u1eadn \u0111c \u1ea5n v\u00f4 th\u1...",2026-08-04 15:39:57.436653,open,None,None,None,giao_dich
21,5fcc6612-2e1a-4fca-96dc-60aa13dbf0ff,2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa,Thái độ / chất lượng phục vụ của nhân viên,"9 phản hồi tiêu cực liên quan đến ""thái độ / chất lượng phục vụ của nhân viên"".",11,up,medium,needs_review,0.73,[],"[""\u0111\u0103ng nh\u1eadp thi\u1ebft b\u1ecb m\u1edbi ph\u1ea3i qu\u00e9t nfc . nhi\u1ec1u ng\u01b0\u1eddi nh\u01b0...",2026-08-04 15:39:57.436653,open,None,None,None,nhan_vien
22,19f30195-9a2b-4176-a7da-1d5a4c798611,0787eded-c5f9-4d91-8987-54f88da239b7,Lỗi ứng dụng / hiệu năng,"98 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",114,up,medium,needs_review,0.79,[],"[""ng\u00e2n h\u00e0ng d\u1edf \u00f2m g\u1eedi ti\u1ec1n l\u1ed7i ho\u00e0i r\u00fat c\u0169ng k r\u00fat dc ? doo t...",2026-08-04 15:39:57.457752,open,None,None,None,ung_dung
23,2165446e-99dd-45bf-acd2-b3e0513e65d6,0787eded-c5f9-4d91-8987-54f88da239b7,Lỗi đăng nhập / xác thực,"46 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",50,up,medium,needs_review,0.78,[],"[""s\u00e0i r\u1ea5t t\u1ed1t nhg l\u00e2u l\u00e2u b\u1ecb l\u1ed7i \u0111\u0103ng nh\u1eadp l\u00e0 b\u1ecb out ra ...",2026-08-04 15:39:57.457752,open,None,None,None,dang_nhap
24,a631e951-40a9-4139-8310-1fcc9d552fdf,0787eded-c5f9-4d91-8987-54f88da239b7,Chất lượng dịch vụ nói chung,"117 phản hồi tiêu cực liên quan đến ""chất lượng dịch vụ nói chung"".",129,up,medium,needs_review,0.77,[],"[""ch\u01b0a th\u1ea5y ng\u00e2n h\u00e0ng n\u00e0o m\u00e0 x\u00e1c minh khu\u00f4n m\u1eb7t t\u1ec7, l\u1ed7i nh\u0...",2026-08-04 15:39:57.457752,open,None,None,None,dich_vu
25,986907d9-ccf4-429a-980a-9cc55f59a3af,0787eded-c5f9-4d91-8987-54f88da239b7,Chính sách / biểu phí,"17 phản hồi tiêu cực liên quan đến ""chính sách / biểu phí"".",20,up,medium,needs_review,0.78,[],"[""Th\u1ebb atm th\u01b0\u1eddng ph\u00ed 99k. Th\u00eam ph\u00ed qu\u1ea3n l\u00ed th\u1ebb 8,8k s\u00e0i c\u1ee9 t\...",2026-08-04 15:39:57.457752,open,None,None,None,chinh_sach
26,599f6718-d69b-46b4-987d-a2c359ad433b,0787eded-c5f9-4d91-8987-54f88da239b7,Thái độ / chất lượng phục vụ của nhân viên,"59 phản hồi tiêu cực liên quan đến ""thái độ / chất lượng phục vụ của nhân viên"".",62,up,high,needs_review,0.77,[],"[""Qu\u00e1 t\u1ec7 ch\u0103m s\u00f3c kh\u00e1ch h\u00e0ng cho c\u00f3 l\u1ec7 kh\u00f4ng gi\u1ea3i quy\u1ebft v\u1e...",2026-08-04 15:39:57.457752,open,None,None,None,nhan_vien
27,b846dcb2-a994-4eeb-a95c-7acaf012a6ef,0787eded-c5f9-4d91-8987-54f88da239b7,Lỗi giao dịch / chuyển tiền,"97 phản hồi tiêu cực liên quan đến ""lỗi giao dịch / chuyển tiền"".",104,up,high,needs_review,0.77,[],"[""C\u00e1i c\u0103n b\u1ea3n nh\u1ea5t l\u00e0 t\u1ed1i \u01b0u th\u00ec l\u1ea1i k\u00e9m, hay b\u1ecb tho\u00e1t a...",2026-08-04 15:39:57.457752,open,None,None,None,giao_dich
28,3f40d9da-1c6e-47c9-9375-3fb20f6142fe,cdca391f-4bcc-44a6-88b8-0b26541a8af2,Chính sách / biểu phí,"6 phản hồi tiêu cực liên quan đến ""chính sách / biểu phí"".",7,up,medium,needs_review,0.78,[],"[""ok, \u00edt l\u1ed7i m\u00e0 kh t\u00ednh ph\u1ee5 ph\u00ed, ck nhanh"", ""V\u00e0i h\u00f4m l\u1ea1i b\u00e1o c\u1e...",2026-08-04 16:34:25.301477,open,None,None,None,chinh_sach
29,72aab8da-7c97-4a33-8c9f-b4c40b656c6e,cdca391f-4bcc-44a6-88b8-0b26541a8af2,Bảo mật / khoá tài khoản,"7 phản hồi tiêu cực liên quan đến ""bảo mật / khoá tài khoản"".",7,up,medium,needs_review,0.81,[],"[""Ban \u0111\u1ea7u x\u00e0i ngon nh\u01b0ng v\u1ec1 sau c\u00e0ng t\u1ec7. 3 th\u1ee9: Chuy\u1ec3n ti\u1ec1n th\u01...",2026-08-04 16:53:09.653172,open,None,None,None,bao_mat
30,a82c05c7-7b7d-4dd0-a474-795874d74e32,ef9fca45-9e13-4c08-b48a-537e337f6e94,Chính sách / biểu phí,"5 phản hồi tiêu cực liên quan đến ""chính sách / biểu phí"".",5,flat,high,needs_review,0.75,[],"[""Ngh\u0129 sao \u0111\u1ed5i \u0111i\u1ec7n tho\u1ea1i m\u00e0 g\u1eedi y\u00eau c\u1ea7u \u0111\u1ed5i thi\u1ebft ...",2026-08-04 17:00:34.559235,open,None,None,None,chinh_sach
31,30b3833e-7cf1-426b-82c2-63bd3d9f1837,f8b8a06a-fe69-49d4-bf36-0d44a3578a77,Bảo mật / khoá tài khoản,"6 phản hồi tiêu cực liên quan đến ""bảo mật / khoá tài khoản"".",6,up,medium,needs_review,0.81,[],"[""MbBank s\u1edf h\u1eefu c\u00f4ng ty b\u1ea3o hi\u1ec3m MB Ageas l\u1eeba \u0111\u1ea3o ng\u01b0\u1eddi ti\u00eau ...",2026-08-04 17:06:01.611093,open,None,None,None,bao_mat
32,08678865-9ca8-4903-972f-844d501e83bf,2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa,Bảo mật / khoá tài khoản,"2 phản hồi tiêu cực liên quan đến ""bảo mật / khoá tài khoản"".",2,flat,medium,needs_review,0.73,[],"[""Ng\u00e2n h\u00e0ng l\u1eeba \u0111\u1ea3o qu\u00e1 t\u1ec7"", ""ng\u00e2n h\u00e0ng ch\u00f3 l\u1eeba \u0111\u1ea3o""]",2026-08-04 17:12:37.985139,open,None,None,None,bao_mat
33,e0381288-5f15-4636-bf70-1df64105e5ea,2c9bb6d6-5b0d-4da8-9cd9-1467b8ca55aa,Chính sách / biểu phí,"3 phản hồi tiêu cực liên quan đến ""chính sách / biểu phí"".",3,flat,medium,needs_review,0.80,[],"[""Ch\u1eafc b\u1ecf ng\u00e2n h\u00e0ng n\u00e0y v\u00e0 ko bao gi\u1edd d\u00f9ng l\u1ea1i ph\u00ed d\u1ecbch v\u1e...",2026-08-04 17:12:37.985139,open,None,None,None,chinh_sach
34,0e4e38c1-b0b0-4cde-aa00-6f7c37cf4752,0787eded-c5f9-4d91-8987-54f88da239b7,Bảo mật / khoá tài khoản,"17 phản hồi tiêu cực liên quan đến ""bảo mật / khoá tài khoản"".",17,up,medium,needs_review,0.78,[],"[""m\u00ecnh \u0111\u00e3 kho\u00e1 th\u1ebb t\u1eeb r\u1ea5t l\u00e2u k s\u1eed d\u1ee5ng nh\u01b0ng v\u1eabn tr\u1e...",2026-08-04 17:19:29.533648,open,None,None,None,bao_mat

--- Table: notifications (42 rows, 8 cols) ---

,id,topic_id,pain_point_id,channel,title,message,sent_at,read
0,04399cd9-c5ad-4d92-9853-00f3c141584c,cdca391f-4bcc-44a6-88b8-0b26541a8af2,0c3debdb-794e-4798-a2a0-2042fc6d2265,both,Lỗi đăng nhập / xác thực,"12 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",2026-08-04 15:39:57.380005,0
1,932de989-6cc5-4439-b46a-32180c969344,cdca391f-4bcc-44a6-88b8-0b26541a8af2,9156b649-8497-4f98-b983-eb4c2d8b5d3b,both,Lỗi ứng dụng / hiệu năng,"13 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",2026-08-04 15:39:57.380005,0
2,ecc99a2f-efd6-4298-8ead-bd2e555ab508,cdca391f-4bcc-44a6-88b8-0b26541a8af2,32aab6ba-5085-4f94-bd51-147426da9272,both,Lỗi giao dịch / chuyển tiền,"15 phản hồi tiêu cực liên quan đến ""lỗi giao dịch / chuyển tiền"".",2026-08-04 15:39:57.380005,0
3,1506612d-5d82-4508-b653-c1ff5f0c23d0,cdca391f-4bcc-44a6-88b8-0b26541a8af2,0ae192bb-9e54-4382-857e-746f30dc7025,both,Chất lượng dịch vụ nói chung,"17 phản hồi tiêu cực liên quan đến ""chất lượng dịch vụ nói chung"".",2026-08-04 15:39:57.380005,0
4,628bf9b1-b066-476f-848f-ea8ba20d0a3f,ef9fca45-9e13-4c08-b48a-537e337f6e94,0d72313a-a220-4390-9f59-259b5cfe3e4d,both,Lỗi ứng dụng / hiệu năng,"26 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",2026-08-04 15:39:57.408864,0
...,...,...,...,...,...,...,...,...
37,9ee29e10-fecb-40be-a700-f4e1d430d49f,0787eded-c5f9-4d91-8987-54f88da239b7,ad3b1cc8-9fd1-41e6-a3d9-40e35f7185cd,both,Lỗi đăng nhập / xác thực,"46 phản hồi tiêu cực liên quan đến ""lỗi đăng nhập / xác thực"".",2026-08-04 17:19:29.535660,0
38,8eec7509-b12c-43c0-b25b-6b3e998cb566,0787eded-c5f9-4d91-8987-54f88da239b7,0e4e38c1-b0b0-4cde-aa00-6f7c37cf4752,both,Bảo mật / khoá tài khoản,"17 phản hồi tiêu cực liên quan đến ""bảo mật / khoá tài khoản"".",2026-08-04 17:19:29.535660,0
39,8a8d9cfe-4a97-46d2-b087-27244e80331b,0787eded-c5f9-4d91-8987-54f88da239b7,69293a43-73e7-4873-8374-350d417f66fe,both,Lỗi ứng dụng / hiệu năng,"98 phản hồi tiêu cực liên quan đến ""lỗi ứng dụng / hiệu năng"".",2026-08-04 17:19:29.535660,0
40,8ccd6547-5176-419c-ac81-7118d6aeb4d5,0787eded-c5f9-4d91-8987-54f88da239b7,e29414ca-506c-4197-b4e0-e786306195a2,both,Thái độ / chất lượng phục vụ của nhân viên,"59 phản hồi tiêu cực liên quan đến ""thái độ / chất lượng phục vụ của nhân viên"".",2026-08-04 17:19:29.535660,0
41,7f6824d5-ebf3-4081-a1df-8787eeab3d53,0787eded-c5f9-4d91-8987-54f88da239b7,b4011456-ff4c-4220-a202-d34935b77861,both,Chính sách / biểu phí,"17 phản hồi tiêu cực liên quan đến ""chính sách / biểu phí"".",2026-08-04 17:19:29.535660,0

In [ ]:
Các bảng hiện có trong DB này phục vụ các chức năng sau:

- `topics`: lưu thông tin các chủ đề / lĩnh vực đang theo dõi. Thường chứa id, người quản lý/owner, tên chủ đề, và các thông tin metadata khác.

- `posts`: lưu các bản ghi bài viết/đoạn hội thoại/mention thực tế thu thập được từ social listening. Nó liên kết với `topic_id`, chứa nội dung, nguồn kênh, thời gian, và các thuộc tính liên quan đến sentiment/feedback.

- `pain_points`: lưu các “điểm đau” / vấn đề cụ thể thuộc về một topic. Mỗi bản ghi gắn với `topic_id` và mô tả một vấn đề như lỗi đăng nhập, hiệu năng, bảo mật, v.v.

- `notifications`: lưu các thông báo cảnh báo/alert liên quan đến topic và pain point. Có các trường như `channel`, `title`, `message`, `sent_at`, và `read` để quản lý việc gửi và trạng thái đã đọc.

Nói ngắn gọn: `topics` là nhóm chủ đề; `posts` là dữ liệu thu thập; `pain_points` là các vấn đề cụ thể; `notifications` là cảnh báo dựa trên vấn đề đó.

In [ ]:
`pain_points` lưu mỗi bản ghi là một “điểm đau” / vấn đề cụ thể của một `topic`.

Thông thường:
- `id`: khóa chính của pain point
- `topic_id`: liên kết về `topics`
- `title`: tên / mô tả ngắn gọn vấn đề
- các trường khác có thể là mô tả chi tiết, loại vấn đề, metadata…

Nói cách khác: `pain_points` không phải là post, mà là bảng định nghĩa các vấn đề cụ thể (ví dụ: lỗi đăng nhập, hiệu năng, bảo mật) gắn với một chủ đề theo dõi.

In [ ]:
Vì người dùng chỉ đăng phản hồi đánh giá app nên `topic` và `pain_point` phải được suy ra từ nội dung đó, chứ không phải tự nhiên có sẵn.

Thông thường quy trình sẽ là:

- `topics` là những nhóm chủ đề bạn quan tâm theo dõi (ví dụ: trải nghiệm đăng nhập, hiệu năng, bảo mật, thanh toán…).
- `pain_points` là các vấn đề cụ thể trong từng topic (ví dụ: “lỗi đăng nhập”, “chậm khởi động”, “khoá tài khoản”, “phí ẩn”).
- Dữ liệu đánh giá trong `posts` / `notifications.message` chứa văn bản phản hồi.
- Một bước xử lý/nghiên cứu sẽ phân tích văn bản đó rồi gán `topic_id` và `pain_point_id`.

Cách gán có thể là:

- quy tắc từ khóa: nếu review chứa “đăng nhập”, “mật khẩu”, “auth” -> gán vào topic/pain point đăng nhập;
- phân loại văn bản NLP hoặc model machine learning;
- đánh dấu thủ công / annotation bởi analyst;
- kết hợp với sentiment để biết đây là phản hồi tiêu cực và cần tạo alert.

Vì vậy, nếu chỉ nhìn vào feedback text, bạn phải dùng thuật toán hoặc quy tắc để xác định:
- người dùng đang nói về lĩnh vực gì (`topic`),
- vấn đề cụ thể nào đang xảy ra (`pain_point`).

Trong DB hiện tại, bảng `notifications` đã lưu kết quả gán đó: mỗi bản ghi có `topic_id` và `pain_point_id`, nghĩa là việc xác định đã được thực hiện trước đó.

In [ ]:
Trong notebook này, không có đoạn code thực hiện gán `topic_id` / `pain_point_id` từ `message` trực tiếp.

Thực tế là trong `notifications` đã có sẵn:
- `topic_id`
- `pain_point_id`

Nên cách gán ở đây là: dữ liệu đã được gán trước khi nằm trong DB, và notebook chỉ đang đọc/hiển thị các giá trị đó.

Nếu dựa vào mô tả chung, cách gán có thể là:
- quy tắc từ khóa,
- NLP / phân loại văn bản,
- hoặc gán thủ công.

Nhưng trong bộ này, ta chỉ thấy kết quả gán đã có sẵn trong bảng, không phải thực hiện lại trong notebook.